Positions on grid for demo
CoronaTeam/CoronaGame pull request #82
Opened 2020-04-02 19:33 UTC by lucieho

This PR adds a test class that uploads fake users with their fake positions to the Firestore Livegrid.
This is for demo purposes. 
Fake users are all located at EPFL, either infected either not.
1 area with a lot of users, another with less.

2020-04-08 19:44 UTC, AdrienRem reviewed
HI ! I don't understand why you changed the FirebaseOfflineCacheTest file. Could you clarify ?

2020-04-09 07:25 UTC, lucieho commented
> HI ! I don't understand why you changed the FirebaseOfflineCacheTest file. Could you clarify ?
HI ! 
I didn't understand why uploads from DataForDemo were not appearing on Firestore after several attempts. I decided to test, in FirebaseOfflineCacheTest, that the data was retrieved/written from/to the Firestore backend server and not from/to the local cache. 
(I had to add a few lines of code in synchronizeLocalChangeWithBackendWhenBackOnline() for this)

2020-04-09 13:28 UTC, AdrienRem approved these changes
Okay, Thanks for your explanation !

2020-04-09 14:01 UTC, TheBlueHawk requested changes
Apart the little refactoring needed, good job, this will be incredibly useful for next demos!

2020-04-09 14:01 UTC, TheBlueHawk commented on app/src/androidTest/java/ch/epfl/sdp/DataForDemo.java
> +     @Test
First part (dense location) looks good to me, second one can be improved by extracting a method for the upload of the couple carrier-location

2020-04-09 14:01 UTC, TheBlueHawk commented on app/src/androidTest/java/ch/epfl/sdp/DataForDemo.java
> +     @Test
This can be reduced using the suggestion above

2020-04-10 09:19 UTC, lucieho commented
Thanks, extract method done.

2020-04-10 12:36 UTC, TheBlueHawk approved these changes

2020-04-10 13:08 UTC, merged